# Práctica Clase 3

## Numpy

In [16]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

A partir de una lista podemos crear un arreglo de numpy

In [17]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [18]:
#Se puede hacer con los dos
print(lista[3])
print(arreglo[3])

3
3


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [19]:
arreglo = np.arange(8)
print(arreglo)

[0 1 2 3 4 5 6 7]


In [21]:
secuencia = list(range(8))
secuencia

[0, 1, 2, 3, 4, 5, 6, 7]

In [22]:
secuencia = []
for i in range(8):
    secuencia.append(i)
secuencia

[0, 1, 2, 3, 4, 5, 6, 7]

In [23]:
secuencia = [i for i in range(8)]
secuencia

[0, 1, 2, 3, 4, 5, 6, 7]

In [27]:
cuadrados = [i**2 for i in range(8)]
cuadrados

[0, 1, 4, 9, 16, 25, 36, 49]

Algunas cosas que se pueden hacer con arreglos pero no con las listas:

1. Sumarle un mismo elemento

In [24]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [25]:
arreglo = arreglo + 1

In [26]:
arreglo

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Elevar al cuadrado todos los elementos

In [28]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [29]:
arreglo**2

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [34]:
#Cosas que se pueden hacer con listas pero no con Arrays.
elementos = [2,4,8,'Hola']
elementos.append(89)
elementos
#arreglo.append(89)

[2, 4, 8, 'Hola', 89]

3. Sumar todos los elementos

In [31]:
print(arreglo.sum())
#print(lista.sum())
print(sum(lista))

36
15


In [35]:
n = 0
for e in lista:
    n = n + e
print(n)

15


In [36]:
arreglo.shape

(8,)

In [37]:
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (3, 6) 



In [39]:
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1 2 3 4 5 6]] . Shape = (1, 6) 



In [40]:
arreglo = np.array([[1,2,3,4,5,6]]).T #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [41]:
#¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)?

print('Arreglo de (n,)')
arreglo = np.array([1,2,3,4,5,6])
print(arreglo,'. Shape =', arreglo.shape, "\n") # "\n" imprime un salto de linea

print('Arreglo de (2,n)')
arreglo = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape, "\n")

print('Arreglo de (n,1)')
arreglo = np.array([[1,2,3,4,5,6]]) #notar los corchetes extras
print(arreglo.T,'. Shape =', arreglo.T.shape, "\n")   #notar .T, que significa transpuesto


Arreglo de (n,)
[1 2 3 4 5 6] . Shape = (6,) 

Arreglo de (2,n)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] . Shape = (2, 6) 

Arreglo de (n,1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1) 



In [42]:
### EXTRA 1###
#Trasponer no es la unica forma de crear un arreglo de forma (n,1)'''
arreglo = np.array([[1],[2],[3],[4],[5],[6]]) #notar los corchetes extras
print(arreglo,'. Shape =', arreglo.shape)   #notar .T, que significa transpuesto

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] . Shape = (6, 1)


In [43]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a1.shape

(2, 4)

In [44]:
a2 = np.array([[1,2,3,4],[5,6,7,8]])
a2.shape

(2, 4)

In [45]:
a3 = a1 * a2
a3.shape

(2, 4)

In [46]:
a3

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [47]:
arreglo1 = np.arange(10)
arreglo1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arreglo2 = np.linspace(0,9,100)
print(arreglo2)
#print(arreglo2.size)
#print(len(arreglo2))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.18181818

In [53]:
#Bonus Track
#numero = int(3.8)
numero = round(3.8)
numero

4

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son divisibles por 3<br>
Pista: mask

In [56]:
serie = np.arange(10,101)
divisibles = serie [serie%3==0]
#serie
divisibles

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60,
       63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [57]:
ceros = np.zeros((5,10), dtype=int)
ceros

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
ceros[(1,3), :] = 1
ceros[: ,(2,7)] = 2
ceros

array([[0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0]])

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100

Para explorar las funciones de creación de datos aleatorios:
https://numpy.org/doc/stable/reference/random/legacy.html

In [59]:
a = np.random.random((4,2,3)) * 100 + 100
a

array([[[150.02646071, 197.59099807, 140.24019064],
        [148.75074767, 111.01952557, 169.94805376]],

       [[167.45109496, 123.19217752, 104.47045397],
        [112.08577752, 168.7073443 , 116.80038368]],

       [[123.3763951 , 161.81225908, 108.0231501 ],
        [143.27363021, 147.04184275, 188.00431908]],

       [[165.11669524, 196.32842229, 130.94563415],
        [150.59248112, 109.86588892, 114.75816157]]])

In [18]:
a = np.random.random((4,4))

In [19]:
a

array([[0.48673571, 0.50465005, 0.33227167, 0.86611167],
       [0.14502147, 0.13692842, 0.56804006, 0.89177045],
       [0.78692331, 0.25942502, 0.88516122, 0.32876297],
       [0.78919257, 0.64347772, 0.02402004, 0.66363368]])

In [20]:
a = np.array([[10,200,30,45,5,50],[5,20,30,40,50,0],[5,20,30,40,50,0],[5,20,30,40,50,0]], dtype=np.int8)

In [115]:
a

array([[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]], dtype=int16)

In [21]:
a.sum()

519

In [22]:
a.std()

23.924904214367643

In [23]:
a.sort(axis=1)

In [24]:
a

array([[-56,   5,  10,  30,  45,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50]], dtype=int8)

In [25]:
a.sort(axis=0)
a

array([[-56,   5,  10,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  40,  50],
       [  0,   5,  20,  30,  45,  50]], dtype=int8)

In [26]:
a[1:3,0:3]

array([[ 0,  5, 20],
       [ 0,  5, 20]], dtype=int8)

In [27]:
l =   [[ 10, 200,  30,  45,   5, 100],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0],
       [  5,  20,  30,  40,  50,   0]]

In [28]:
a = np.array([l])

In [31]:
a.shape

(1, 4, 6)

In [32]:
a.reshape(24)

array([ 10, 200,  30,  45,   5, 100,   5,  20,  30,  40,  50,   0,   5,
        20,  30,  40,  50,   0,   5,  20,  30,  40,  50,   0])

In [33]:
a = np.matrix([[1,2,3,4,5,6]]) 
print(a) 

[[1 2 3 4 5 6]]


In [34]:
b = np.matrix([[1],[2],[3],[4],[5],[6]]) 
print(b) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [35]:
c = a * b 
print(c) 

[[91]]


In [36]:
d = b * a 
print(d)

[[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
